# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Readhub-ly' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Readhub-ly
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'YYKit'
    pod 'MJRefresh'
    pod 'Masonry'

  target 'Readhub-lyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Readhub-lyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
